services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: mydb
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: ./server
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: mydb
      PGPASSWORD: postgres_password
      PGPORT: 5432
    networks:
      - app-network

  client:
    container_name: client
    stdin_open: true
    build:
      context: ./client
    depends_on:
      - api
    volumes:
      - ./client:/app
    environment:
      REACT_APP_API_URL: http://api:5000
    networks:
      - app-network

  nginx:
    container_name: nginx-postgres
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
    ports:
      - "5000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres-data:
